from __future__ import annotations
from enum import Enum

class LightRigPresetType(Enum):
    """Constants which define light preset types."""
    NOT_DEFINED = 'NotDefined'
    BALANCED = 'Balanced'
    BRIGHT_ROOM = 'BrightRoom'
    CHILLY = 'Chilly'
    CONTRASTING = 'Contrasting'
    FLAT = 'Flat'
    FLOOD = 'Flood'
    FREEZING = 'Freezing'
    GLOW = 'Glow'
    HARSH = 'Harsh'
    LEGACY_FLAT1 = 'LegacyFlat1'
    LEGACY_FLAT2 = 'LegacyFlat2'
    LEGACY_FLAT3 = 'LegacyFlat3'
    LEGACY_FLAT4 = 'LegacyFlat4'
    LEGACY_HARSH1 = 'LegacyHarsh1'
    LEGACY_HARSH2 = 'LegacyHarsh2'
    LEGACY_HARSH3 = 'LegacyHarsh3'
    LEGACY_HARSH4 = 'LegacyHarsh4'
    LEGACY_NORMAL1 = 'LegacyNormal1'
    LEGACY_NORMAL2 = 'LegacyNormal2'
    LEGACY_NORMAL3 = 'LegacyNormal3'
    LEGACY_NORMAL4 = 'LegacyNormal4'
    MORNING = 'Morning'
    SOFT = 'Soft'
    SUNRISE = 'Sunrise'
    SUNSET = 'Sunset'
    THREE_PT = 'ThreePt'
    TWO_PT = 'TwoPt'
