from __future__ import annotations
from enum import Enum

class NumberedBulletStyle(Enum):
    """Represents the style of the numbered bullets."""
    NOT_DEFINED = 'NotDefined'  # Not defined.
    BULLET_ALPHA_LC_PERIOD = 'BulletAlphaLCPeriod'  # Lowercase alphabetical characters with a period. Sample: a., b., c., ...
    BULLET_ALPHA_UC_PERIOD = 'BulletAlphaUCPeriod'  # Uppercase alphabetical characters with a period. Sample: A., B., C., ...
    BULLET_ARABIC_PAREN_RIGHT = 'BulletArabicParenRight'  # Arabic numerals with closing parenthesis. Sample: 1), 2), 3), ...
    BULLET_ARABIC_PERIOD = 'BulletArabicPeriod'  # Arabic numerals with a period. Sample: 1., 2., 3., ...
    BULLET_ROMAN_LC_PAREN_BOTH = 'BulletRomanLCParenBoth'  # Lowercase Roman numerals with both parentheses. Sample: (i), (ii), (iii), ...
    BULLET_ROMAN_LC_PAREN_RIGHT = 'BulletRomanLCParenRight'  # Lowercase Roman numerals with closing parenthesis. Sample: i), ii), iii), ...
    BULLET_ROMAN_LC_PERIOD = 'BulletRomanLCPeriod'  # Lowercase Roman numerals with period. Sample: i., ii., iii., ...
    BULLET_ROMAN_UC_PERIOD = 'BulletRomanUCPeriod'  # Uppercase Roman numerals with period. Sample: I., II., III., ...
    BULLET_ALPHA_LC_PAREN_BOTH = 'BulletAlphaLCParenBoth'  # Lowercase alphabetical characters with both parentheses. Sample: (a), (b), (c), ...
    BULLET_ALPHA_LC_PAREN_RIGHT = 'BulletAlphaLCParenRight'  # Lowercase alphabetical characters with closing parenthesis. Sample: a), b), c), ...
    BULLET_ALPHA_UC_PAREN_BOTH = 'BulletAlphaUCParenBoth'  # Uppercase alphabetical characters with both parentheses. Sample: (A), (B), (C), ...
    BULLET_ALPHA_UC_PAREN_RIGHT = 'BulletAlphaUCParenRight'  # Uppercase alphabetical characters with closing parenthesis. Sample: A), B), C), ...
    BULLET_ARABIC_PAREN_BOTH = 'BulletArabicParenBoth'  # Arabic numerals with both parentheses. Sample: (1), (2), (3), ...
    BULLET_ARABIC_PLAIN = 'BulletArabicPlain'  # Arabic numerals. Sample: 1, 2, 3, ...
    BULLET_ROMAN_UC_PAREN_BOTH = 'BulletRomanUCParenBoth'  # Uppercase Roman numerals with both parentheses. Sample: (I), (II), (III), ...
    BULLET_ROMAN_UC_PAREN_RIGHT = 'BulletRomanUCParenRight'  # Uppercase Roman numerals with closing parenthesis. Sample: I), II), III), ...
    BULLET_SIMP_CHIN_PLAIN = 'BulletSimpChinPlain'  # Simplified Chinese without a period.
    BULLET_SIMP_CHIN_PERIOD = 'BulletSimpChinPeriod'  # Simplified Chinese with a period.
    BULLET_CIRCLE_NUM_DB_PLAIN = 'BulletCircleNumDBPlain'  # Double-byte circled number for values up to 10, from 11 - arabic numbers.
    BULLET_CIRCLE_NUM_WD_WHITE_PLAIN = 'BulletCircleNumWDWhitePlain'  # Text colored number with same color circle drawn around it (Wingdings white circle numbers). From 11 - arabic numbers.
    BULLET_CIRCLE_NUM_WD_BLACK_PLAIN = 'BulletCircleNumWDBlackPlain'  # Shadow color number with circular background of normal text color (Wingdings black circle numbers).
    BULLET_TRAD_CHIN_PLAIN = 'BulletTradChinPlain'  # Traditional Chinese without a period.
    BULLET_TRAD_CHIN_PERIOD = 'BulletTradChinPeriod'  # Traditional Chinese with a period.
    BULLET_ARABIC_ALPHA_DASH = 'BulletArabicAlphaDash'  # Arabic language alphabetical characters with a dash.
    BULLET_ARABIC_ABJAD_DASH = 'BulletArabicAbjadDash'  # Arabic Abjad alphabets with a dash.
    BULLET_HEBREW_ALPHA_DASH = 'BulletHebrewAlphaDash'  # Hebrew language alphabetical characters with a dash.
    BULLET_KANJI_KOREAN_PLAIN = 'BulletKanjiKoreanPlain'  # Japanese/Korean numbers without a period.
    BULLET_KANJI_KOREAN_PERIOD = 'BulletKanjiKoreanPeriod'  # Japanese/Korean numbers with a period.
    BULLET_ARABIC_DB_PLAIN = 'BulletArabicDBPlain'  # Double-byte Arabic numbering scheme (no punctuation).
    BULLET_ARABIC_DB_PERIOD = 'BulletArabicDBPeriod'  # Double-byte Arabic numbering scheme with double-byte period.
    BULLET_THAI_ALPHA_PERIOD = 'BulletThaiAlphaPeriod'  # Thai alphabet period.
    BULLET_THAI_ALPHA_PAREN_RIGHT = 'BulletThaiAlphaParenRight'  # Thai alphabet parentheses - right.
    BULLET_THAI_ALPHA_PAREN_BOTH = 'BulletThaiAlphaParenBoth'  # Thai alphabet parentheses - both.
    BULLET_THAI_NUM_PERIOD = 'BulletThaiNumPeriod'  # Thai numerical period.
    BULLET_THAI_NUM_PAREN_RIGHT = 'BulletThaiNumParenRight'  # Thai numerical parentheses - right.
    BULLET_THAI_NUM_PAREN_BOTH = 'BulletThaiNumParenBoth'  # Thai numerical parentheses - both.
    BULLET_HINDI_ALPHA_PERIOD = 'BulletHindiAlphaPeriod'  # Hindi alphabet period - vowels.
    BULLET_HINDI_NUM_PERIOD = 'BulletHindiNumPeriod'  # Hindi numerical period.
    BULLET_KANJI_SIMP_CHIN_DB_PERIOD = 'BulletKanjiSimpChinDBPeriod'  # Kanji Simple Chinese DBPeriod.
    BULLET_HINDI_NUM_PAREN_RIGHT = 'BulletHindiNumParenRight'  # Hindi numerical parentheses - right.
    BULLET_HINDI_ALPHA_1_PERIOD = 'BulletHindiAlpha1Period'  # Hindi alphabet period - consonants.
