from __future__ import annotations
from enum import Enum

class ShapeType(Enum):
    """Represents preset geometry of geometry shapes."""
    NOT_DEFINED = 'NotDefined'  # Not defined.
    CUSTOM = 'Custom'  # Custom shape. This is return-only value.
    LINE = 'Line'  # Line Shape.
    LINE_INVERSE = 'LineInverse'  # Line Inverse Shape.
    TRIANGLE = 'Triangle'  # Triangle Shape.
    RIGHT_TRIANGLE = 'RightTriangle'  # Right Triangle Shape.
    RECTANGLE = 'Rectangle'  # Rectangle Shape.
    DIAMOND = 'Diamond'  # Diamond Shape.
    PARALLELOGRAM = 'Parallelogram'  # Parallelogram Shape.
    TRAPEZOID = 'Trapezoid'  # Trapezoid Shape.
    NON_ISOSCELES_TRAPEZOID = 'NonIsoscelesTrapezoid'  # Non-Isosceles Trapezoid Shape.
    PENTAGON = 'Pentagon'  # Pentagon Shape.
    HEXAGON = 'Hexagon'  # Hexagon Shape.
    HEPTAGON = 'Heptagon'  # Heptagon Shape.
    OCTAGON = 'Octagon'  # Octagon Shape.
    DECAGON = 'Decagon'  # Decagon Shape.
    DODECAGON = 'Dodecagon'  # Dodecagon Shape.
    FOUR_POINTED_STAR = 'FourPointedStar'  # Four Pointed Star Shape.
    FIVE_POINTED_STAR = 'FivePointedStar'  # Five Pointed Star Shape.
    SIX_POINTED_STAR = 'SixPointedStar'  # Six Pointed Star Shape.
    SEVEN_POINTED_STAR = 'SevenPointedStar'  # Seven Pointed Star Shape.
    EIGHT_POINTED_STAR = 'EightPointedStar'  # Eight Pointed Star Shape.
    TEN_POINTED_STAR = 'TenPointedStar'  # Ten Pointed Star Shape.
    TWELVE_POINTED_STAR = 'TwelvePointedStar'  # Twelve Pointed Star Shape.
    SIXTEEN_POINTED_STAR = 'SixteenPointedStar'  # Sixteen Pointed Star Shape.
    TWENTY_FOUR_POINTED_STAR = 'TwentyFourPointedStar'  # Twenty Four Pointed Star Shape.
    THIRTY_TWO_POINTED_STAR = 'ThirtyTwoPointedStar'  # Thirty Two Pointed Star Shape.
    ROUND_CORNER_RECTANGLE = 'RoundCornerRectangle'  # Round Corner Rectangle Shape.
    ONE_ROUND_CORNER_RECTANGLE = 'OneRoundCornerRectangle'  # One Round Corner Rectangle Shape.
    TWO_SAMESIDE_ROUND_CORNER_RECTANGLE = 'TwoSamesideRoundCornerRectangle'  # Two Same-side Round Corner Rectangle Shape.
    TWO_DIAGONAL_ROUND_CORNER_RECTANGLE = 'TwoDiagonalRoundCornerRectangle'  # Two Diagonal Round Corner Rectangle Shape.
    ONE_SNIP_ONE_ROUND_CORNER_RECTANGLE = 'OneSnipOneRoundCornerRectangle'  # One Snip One Round Corner Rectangle Shape.
    ONE_SNIP_CORNER_RECTANGLE = 'OneSnipCornerRectangle'  # One Snip Corner Rectangle Shape.
    TWO_SAMESIDE_SNIP_CORNER_RECTANGLE = 'TwoSamesideSnipCornerRectangle'  # Two Same-side Snip Corner Rectangle Shape.
    TWO_DIAGONAL_SNIP_CORNER_RECTANGLE = 'TwoDiagonalSnipCornerRectangle'  # Two Diagonal Snip Corner Rectangle Shape.
    PLAQUE = 'Plaque'  # Plaque Shape.
    ELLIPSE = 'Ellipse'  # Ellipse Shape.
    TEARDROP = 'Teardrop'  # Teardrop Shape.
    HOME_PLATE = 'HomePlate'  # Home Plate Shape.
    CHEVRON = 'Chevron'  # Chevron Shape.
    PIE_WEDGE = 'PieWedge'  # Pie Wedge Shape.
    PIE = 'Pie'  # Pie Shape.
    BLOCK_ARC = 'BlockArc'  # Block Arc Shape.
    DONUT = 'Donut'  # Donut Shape.
    NO_SMOKING = 'NoSmoking'  # No Smoking Shape.
    RIGHT_ARROW = 'RightArrow'  # Right Arrow Shape.
    LEFT_ARROW = 'LeftArrow'  # Left Arrow Shape.
    UP_ARROW = 'UpArrow'  # Up Arrow Shape.
    DOWN_ARROW = 'DownArrow'  # Down Arrow Shape.
    STRIPED_RIGHT_ARROW = 'StripedRightArrow'  # Striped Right Arrow Shape.
    NOTCHED_RIGHT_ARROW = 'NotchedRightArrow'  # Notched Right Arrow Shape.
    BENT_UP_ARROW = 'BentUpArrow'  # Bent Up Arrow Shape.
    LEFT_RIGHT_ARROW = 'LeftRightArrow'  # Left Right Arrow Shape.
    UP_DOWN_ARROW = 'UpDownArrow'  # Up Down Arrow Shape.
    LEFT_UP_ARROW = 'LeftUpArrow'  # Left Up Arrow Shape.
    LEFT_RIGHT_UP_ARROW = 'LeftRightUpArrow'  # Left Right Up Arrow Shape.
    QUAD_ARROW = 'QuadArrow'  # Quad-Arrow Shape.
    CALLOUT_LEFT_ARROW = 'CalloutLeftArrow'  # Callout Left Arrow Shape.
    CALLOUT_RIGHT_ARROW = 'CalloutRightArrow'  # Callout Right Arrow Shape.
    CALLOUT_UP_ARROW = 'CalloutUpArrow'  # Callout Up Arrow Shape.
    CALLOUT_DOWN_ARROW = 'CalloutDownArrow'  # Callout Down Arrow Shape.
    CALLOUT_LEFT_RIGHT_ARROW = 'CalloutLeftRightArrow'  # Callout Left Right Arrow Shape.
    CALLOUT_UP_DOWN_ARROW = 'CalloutUpDownArrow'  # Callout Up Down Arrow Shape.
    CALLOUT_QUAD_ARROW = 'CalloutQuadArrow'  # Callout Quad-Arrow Shape.
    BENT_ARROW = 'BentArrow'  # Bent Arrow Shape.
    U_TURN_ARROW = 'UTurnArrow'  # U-Turn Arrow Shape.
    CIRCULAR_ARROW = 'CircularArrow'  # Circular Arrow Shape.
    LEFT_CIRCULAR_ARROW = 'LeftCircularArrow'  # Left Circular Arrow Shape.
    LEFT_RIGHT_CIRCULAR_ARROW = 'LeftRightCircularArrow'  # Left Right Circular Arrow Shape.
    CURVED_RIGHT_ARROW = 'CurvedRightArrow'  # Curved Right Arrow Shape.
    CURVED_LEFT_ARROW = 'CurvedLeftArrow'  # Curved Left Arrow Shape.
    CURVED_UP_ARROW = 'CurvedUpArrow'  # Curved Up Arrow Shape.
    CURVED_DOWN_ARROW = 'CurvedDownArrow'  # Curved Down Arrow Shape.
    SWOOSH_ARROW = 'SwooshArrow'  # Swoosh Arrow Shape.
    CUBE = 'Cube'  # Cube Shape.
    CAN = 'Can'  # Can Shape.
    LIGHTNING_BOLT = 'LightningBolt'  # Lightning Bolt Shape.
    HEART = 'Heart'  # Heart Shape.
    SUN = 'Sun'  # Sun Shape.
    MOON = 'Moon'  # Moon Shape.
    SMILEY_FACE = 'SmileyFace'  # Smiley Face Shape.
    IRREGULAR_SEAL1 = 'IrregularSeal1'  # Irregular Seal 1 Shape.
    IRREGULAR_SEAL2 = 'IrregularSeal2'  # Irregular Seal 2 Shape.
    FOLDED_CORNER = 'FoldedCorner'  # Folded Corner Shape.
    BEVEL = 'Bevel'  # Bevel Shape.
    FRAME = 'Frame'  # Frame Shape.
    HALF_FRAME = 'HalfFrame'  # Half Frame Shape.
    CORNER = 'Corner'  # Corner Shape.
    DIAGONAL_STRIPE = 'DiagonalStripe'  # Diagonal Stripe Shape.
    CHORD = 'Chord'  # Chord Shape.
    CURVED_ARC = 'CurvedArc'  # Curved Arc Shape.
    LEFT_BRACKET = 'LeftBracket'  # Left Bracket Shape.
    RIGHT_BRACKET = 'RightBracket'  # Right Bracket Shape.
    LEFT_BRACE = 'LeftBrace'  # Left Brace Shape.
    RIGHT_BRACE = 'RightBrace'  # Right Brace Shape.
    BRACKET_PAIR = 'BracketPair'  # Bracket Pair Shape.
    BRACE_PAIR = 'BracePair'  # Brace Pair Shape.
    STRAIGHT_CONNECTOR1 = 'StraightConnector1'  # Straight Connector 1 Shape.
    BENT_CONNECTOR2 = 'BentConnector2'  # Bent Connector 2 Shape.
    BENT_CONNECTOR3 = 'BentConnector3'  # Bent Connector 3 Shape.
    BENT_CONNECTOR4 = 'BentConnector4'  # Bent Connector 4 Shape.
    BENT_CONNECTOR5 = 'BentConnector5'  # Bent Connector 5 Shape.
    CURVED_CONNECTOR2 = 'CurvedConnector2'  # Curved Connector 2 Shape.
    CURVED_CONNECTOR3 = 'CurvedConnector3'  # Curved Connector 3 Shape.
    CURVED_CONNECTOR4 = 'CurvedConnector4'  # Curved Connector 4 Shape.
    CURVED_CONNECTOR5 = 'CurvedConnector5'  # Curved Connector 5 Shape.
    CALLOUT1 = 'Callout1'  # Callout 1 Shape.
    CALLOUT2 = 'Callout2'  # Callout 2 Shape.
    CALLOUT3 = 'Callout3'  # Callout 3 Shape.
    CALLOUT_1_WITH_ACCENT = 'Callout1WithAccent'  # Callout 1 with Accent Shape.
    CALLOUT_2_WITH_ACCENT = 'Callout2WithAccent'  # Callout 2 with Accent Shape.
    CALLOUT_3_WITH_ACCENT = 'Callout3WithAccent'  # Callout 3 with Accent Shape.
    CALLOUT_1_WITH_BORDER = 'Callout1WithBorder'  # Callout 1 with Border Shape.
    CALLOUT_2_WITH_BORDER = 'Callout2WithBorder'  # Callout 2 with Border Shape.
    CALLOUT_3_WITH_BORDER = 'Callout3WithBorder'  # Callout 3 with Border Shape.
    CALLOUT_1_WITH_BORDER_AND_ACCENT = 'Callout1WithBorderAndAccent'  # Callout 1 with Border and Accent Shape.
    CALLOUT_2_WITH_BORDER_AND_ACCENT = 'Callout2WithBorderAndAccent'  # Callout 2 with Border and Accent Shape.
    CALLOUT_3_WITH_BORDER_AND_ACCENT = 'Callout3WithBorderAndAccent'  # Callout 3 with Border and Accent Shape.
    CALLOUT_WEDGE_RECTANGLE = 'CalloutWedgeRectangle'  # Callout Wedge Rectangle Shape.
    CALLOUT_WEDGE_ROUND_RECTANGLE = 'CalloutWedgeRoundRectangle'  # Callout Wedge Round Rectangle Shape.
    CALLOUT_WEDGE_ELLIPSE = 'CalloutWedgeEllipse'  # Callout Wedge Ellipse Shape.
    CALLOUT_CLOUD = 'CalloutCloud'  # Callout Cloud Shape.
    CLOUD = 'Cloud'  # Cloud Shape.
    RIBBON = 'Ribbon'  # Ribbon Shape.
    RIBBON2 = 'Ribbon2'  # Ribbon 2 Shape.
    ELLIPSE_RIBBON = 'EllipseRibbon'  # Ellipse Ribbon Shape.
    ELLIPSE_RIBBON2 = 'EllipseRibbon2'  # Ellipse Ribbon 2 Shape.
    LEFT_RIGHT_RIBBON = 'LeftRightRibbon'  # Left Right Ribbon Shape.
    VERTICAL_SCROLL = 'VerticalScroll'  # Vertical Scroll Shape.
    HORIZONTAL_SCROLL = 'HorizontalScroll'  # Horizontal Scroll Shape.
    WAVE = 'Wave'  # Wave Shape.
    DOUBLE_WAVE = 'DoubleWave'  # Double Wave Shape.
    PLUS = 'Plus'  # Plus Shape.
    PROCESS_FLOW = 'ProcessFlow'  # Process Flow Shape.
    DECISION_FLOW = 'DecisionFlow'  # Decision Flow Shape.
    INPUT_OUTPUT_FLOW = 'InputOutputFlow'  # Input Output Flow Shape.
    PREDEFINED_PROCESS_FLOW = 'PredefinedProcessFlow'  # Predefined Process Flow Shape.
    INTERNAL_STORAGE_FLOW = 'InternalStorageFlow'  # Internal Storage Flow Shape.
    DOCUMENT_FLOW = 'DocumentFlow'  # Document Flow Shape.
    MULTI_DOCUMENT_FLOW = 'MultiDocumentFlow'  # Multi-Document Flow Shape.
    TERMINATOR_FLOW = 'TerminatorFlow'  # Terminator Flow Shape.
    PREPARATION_FLOW = 'PreparationFlow'  # Preparation Flow Shape.
    MANUAL_INPUT_FLOW = 'ManualInputFlow'  # Manual Input Flow Shape.
    MANUAL_OPERATION_FLOW = 'ManualOperationFlow'  # Manual Operation Flow Shape.
    CONNECTOR_FLOW = 'ConnectorFlow'  # Connector Flow Shape.
    PUNCHED_CARD_FLOW = 'PunchedCardFlow'  # Punched Card Flow Shape.
    PUNCHED_TAPE_FLOW = 'PunchedTapeFlow'  # Punched Tape Flow Shape.
    SUMMING_JUNCTION_FLOW = 'SummingJunctionFlow'  # Summing Junction Flow Shape.
    OR_FLOW = 'OrFlow'  # Or Flow Shape.
    COLLATE_FLOW = 'CollateFlow'  # Collate Flow Shape.
    SORT_FLOW = 'SortFlow'  # Sort Flow Shape.
    EXTRACT_FLOW = 'ExtractFlow'  # Extract Flow Shape.
    MERGE_FLOW = 'MergeFlow'  # Merge Flow Shape.
    OFFLINE_STORAGE_FLOW = 'OfflineStorageFlow'  # Offline Storage Flow Shape.
    ONLINE_STORAGE_FLOW = 'OnlineStorageFlow'  # Online Storage Flow Shape.
    MAGNETIC_TAPE_FLOW = 'MagneticTapeFlow'  # Magnetic Tape Flow Shape.
    MAGNETIC_DISK_FLOW = 'MagneticDiskFlow'  # Magnetic Disk Flow Shape.
    MAGNETIC_DRUM_FLOW = 'MagneticDrumFlow'  # Magnetic Drum Flow Shape.
    DISPLAY_FLOW = 'DisplayFlow'  # Display Flow Shape.
    DELAY_FLOW = 'DelayFlow'  # Delay Flow Shape.
    ALTERNATE_PROCESS_FLOW = 'AlternateProcessFlow'  # Alternate Process Flow Shape.
    OFF_PAGE_CONNECTOR_FLOW = 'OffPageConnectorFlow'  # Off-Page Connector Flow Shape.
    BLANK_BUTTON = 'BlankButton'  # Blank Button Shape.
    HOME_BUTTON = 'HomeButton'  # Home Button Shape.
    HELP_BUTTON = 'HelpButton'  # Help Button Shape.
    INFORMATION_BUTTON = 'InformationButton'  # Information Button Shape.
    FORWARD_OR_NEXT_BUTTON = 'ForwardOrNextButton'  # Forward or Next Button Shape.
    BACK_OR_PREVIOUS_BUTTON = 'BackOrPreviousButton'  # Back or Previous Button Shape.
    END_BUTTON = 'EndButton'  # End Button Shape.
    BEGINNING_BUTTON = 'BeginningButton'  # Beginning Button Shape.
    RETURN_BUTTON = 'ReturnButton'  # Return Button Shape.
    DOCUMENT_BUTTON = 'DocumentButton'  # Document Button Shape.
    SOUND_BUTTON = 'SoundButton'  # Sound Button Shape.
    MOVIE_BUTTON = 'MovieButton'  # Movie Button Shape.
    GEAR6 = 'Gear6'  # Gear 6 Shape.
    GEAR9 = 'Gear9'  # Gear 9 Shape.
    FUNNEL = 'Funnel'  # Funnel Shape.
    PLUS_MATH = 'PlusMath'  # Plus Math Shape.
    MINUS_MATH = 'MinusMath'  # Minus Math Shape.
    MULTIPLY_MATH = 'MultiplyMath'  # Multiply Math Shape.
    DIVIDE_MATH = 'DivideMath'  # Divide Math Shape.
    EQUAL_MATH = 'EqualMath'  # Equal Math Shape.
    NOT_EQUAL_MATH = 'NotEqualMath'  # Not Equal Math Shape.
    CORNER_TABS = 'CornerTabs'  # Corner Tabs Shape.
    SQUARE_TABS = 'SquareTabs'  # Square Tabs Shape.
    PLAQUE_TABS = 'PlaqueTabs'  # Plaque Tabs Shape.
    CHART_X = 'ChartX'  # Chart X Shape.
    CHART_STAR = 'ChartStar'  # Chart Star Shape.
    CHART_PLUS = 'ChartPlus'  # Chart Plus Shape.
