from __future__ import annotations
from enum import Enum

class TableStylePreset(Enum):
    """Represents builtin table styles."""
    CUSTOM = 'Custom'  # Table has a custom style. This is return-only value.
    NONE = 'None'  # No style.
    MEDIUM_STYLE_2_ACCENT_1 = 'MediumStyle2Accent1'  # Medium Style 2 - Accent 1.
    MEDIUM_STYLE2 = 'MediumStyle2'  # Medium Style 2.
    NO_STYLE_NO_GRID = 'NoStyleNoGrid'  # No Style, No Grid.
    THEMED_STYLE_1_ACCENT_1 = 'ThemedStyle1Accent1'  # Themed Style 1 - Accent 1.
    THEMED_STYLE_1_ACCENT_2 = 'ThemedStyle1Accent2'  # Themed Style 1 - Accent 2.
    THEMED_STYLE_1_ACCENT_3 = 'ThemedStyle1Accent3'  # Themed Style 1 - Accent 3.
    THEMED_STYLE_1_ACCENT_4 = 'ThemedStyle1Accent4'  # Themed Style 1 - Accent 4.
    THEMED_STYLE_1_ACCENT_5 = 'ThemedStyle1Accent5'  # Themed Style 1 - Accent 5.
    THEMED_STYLE_1_ACCENT_6 = 'ThemedStyle1Accent6'  # Themed Style 1 - Accent 6.
    NO_STYLE_TABLE_GRID = 'NoStyleTableGrid'  # No Style, Table Grid.
    THEMED_STYLE_2_ACCENT_1 = 'ThemedStyle2Accent1'  # Themed Style 2 - Accent 1.
    THEMED_STYLE_2_ACCENT_2 = 'ThemedStyle2Accent2'  # Themed Style 2 - Accent 2.
    THEMED_STYLE_2_ACCENT_3 = 'ThemedStyle2Accent3'  # Themed Style 2 - Accent 3.
    THEMED_STYLE_2_ACCENT_4 = 'ThemedStyle2Accent4'  # Themed Style 2 - Accent 4.
    THEMED_STYLE_2_ACCENT_5 = 'ThemedStyle2Accent5'  # Themed Style 2 - Accent 5.
    THEMED_STYLE_2_ACCENT_6 = 'ThemedStyle2Accent6'  # Themed Style 2 - Accent 6.
    LIGHT_STYLE1 = 'LightStyle1'  # Light Style 1
    LIGHT_STYLE_1_ACCENT_1 = 'LightStyle1Accent1'  # Light Style 1 - Accent 1.
    LIGHT_STYLE_1_ACCENT_2 = 'LightStyle1Accent2'  # Light Style 1 - Accent 2.
    LIGHT_STYLE_1_ACCENT_3 = 'LightStyle1Accent3'  # Light Style 1 - Accent 3.
    LIGHT_STYLE_1_ACCENT_4 = 'LightStyle1Accent4'  # Light Style 1 - Accent 4.
    LIGHT_STYLE_2_ACCENT_5 = 'LightStyle2Accent5'  # Light Style 2 - Accent 5.
    LIGHT_STYLE_1_ACCENT_6 = 'LightStyle1Accent6'  # Light Style 1 - Accent 6.
    LIGHT_STYLE2 = 'LightStyle2'  # Light Style 2.
    LIGHT_STYLE_2_ACCENT_1 = 'LightStyle2Accent1'  # Light Style 2 - Accent 1.
    LIGHT_STYLE_2_ACCENT_2 = 'LightStyle2Accent2'  # Light Style 2 - Accent 2.
    LIGHT_STYLE_2_ACCENT_3 = 'LightStyle2Accent3'  # Light Style 2 - Accent 3.
    MEDIUM_STYLE_2_ACCENT_3 = 'MediumStyle2Accent3'  # Medium Style 2 - Accent 3.
    MEDIUM_STYLE_2_ACCENT_4 = 'MediumStyle2Accent4'  # Medium Style 2 - Accent 4.
    MEDIUM_STYLE_2_ACCENT_5 = 'MediumStyle2Accent5'  # Medium Style 2 - Accent 5.
    LIGHT_STYLE_2_ACCENT_6 = 'LightStyle2Accent6'  # Light Style 2 - Accent 6.
    LIGHT_STYLE_2_ACCENT_4 = 'LightStyle2Accent4'  # Light Style 2 - Accent 4.
    LIGHT_STYLE3 = 'LightStyle3'  # Light Style 3.
    LIGHT_STYLE_3_ACCENT_1 = 'LightStyle3Accent1'  # Light Style 3 - Accent 1.
    MEDIUM_STYLE_2_ACCENT_2 = 'MediumStyle2Accent2'  # Medium Style 2 - Accent 2.
    LIGHT_STYLE_3_ACCENT_2 = 'LightStyle3Accent2'  # Light Style 3 - Accent 2.
    LIGHT_STYLE_3_ACCENT_3 = 'LightStyle3Accent3'  # Light Style 3 - Accent 3.
    LIGHT_STYLE_3_ACCENT_4 = 'LightStyle3Accent4'  # Light Style 3 - Accent 4.
    LIGHT_STYLE_3_ACCENT_5 = 'LightStyle3Accent5'  # Light Style 3 - Accent 5.
    LIGHT_STYLE_3_ACCENT_6 = 'LightStyle3Accent6'  # Light Style 3 - Accent 6.
    MEDIUM_STYLE1 = 'MediumStyle1'  # Medium Style 1.
    MEDIUM_STYLE_1_ACCENT_1 = 'MediumStyle1Accent1'  # Medium Style 1 - Accent 1.
    MEDIUM_STYLE_1_ACCENT_2 = 'MediumStyle1Accent2'  # Medium Style 1 - Accent 2.
    MEDIUM_STYLE_1_ACCENT_3 = 'MediumStyle1Accent3'  # Medium Style 1 - Accent 3.
    MEDIUM_STYLE_1_ACCENT_4 = 'MediumStyle1Accent4'  # Medium Style 1 - Accent 4.
    MEDIUM_STYLE_1_ACCENT_5 = 'MediumStyle1Accent5'  # Medium Style 1 - Accent 5.
    MEDIUM_STYLE_1_ACCENT_6 = 'MediumStyle1Accent6'  # Medium Style 1 - Accent 6.
    MEDIUM_STYLE_2_ACCENT_6 = 'MediumStyle2Accent6'  # Medium Style 2 - Accent 6.
    MEDIUM_STYLE3 = 'MediumStyle3'  # Medium Style 3.
    MEDIUM_STYLE_3_ACCENT_1 = 'MediumStyle3Accent1'  # Medium Style 3 - Accent 1.
    MEDIUM_STYLE_3_ACCENT_2 = 'MediumStyle3Accent2'  # Medium Style 3 - Accent 2.
    MEDIUM_STYLE_3_ACCENT_3 = 'MediumStyle3Accent3'  # Medium Style 3 - Accent 3.
    MEDIUM_STYLE_3_ACCENT_4 = 'MediumStyle3Accent4'  # Medium Style 3 - Accent 4.
    MEDIUM_STYLE_3_ACCENT_5 = 'MediumStyle3Accent5'  # Medium Style 3 - Accent 5.
    MEDIUM_STYLE_3_ACCENT_6 = 'MediumStyle3Accent6'  # Medium Style 3 - Accent 6.
    MEDIUM_STYLE4 = 'MediumStyle4'  # Medium Style 4.
    MEDIUM_STYLE_4_ACCENT_1 = 'MediumStyle4Accent1'  # Medium Style 4 - Accent 1.
    MEDIUM_STYLE_4_ACCENT_2 = 'MediumStyle4Accent2'  # Medium Style 4 - Accent 2.
    MEDIUM_STYLE_4_ACCENT_3 = 'MediumStyle4Accent3'  # Medium Style 4 - Accent 3.
    MEDIUM_STYLE_4_ACCENT_4 = 'MediumStyle4Accent4'  # Medium Style 4 - Accent 4.
    MEDIUM_STYLE_4_ACCENT_5 = 'MediumStyle4Accent5'  # Medium Style 4 - Accent 5.
    MEDIUM_STYLE_4_ACCENT_6 = 'MediumStyle4Accent6'  # Medium Style 4 - Accent 6.
    DARK_STYLE1 = 'DarkStyle1'  # Dark Style 1.
    DARK_STYLE_1_ACCENT_1 = 'DarkStyle1Accent1'  # Dark Style 1 - Accent 1.
    DARK_STYLE_1_ACCENT_2 = 'DarkStyle1Accent2'  # Dark Style 1 - Accent 2.
    DARK_STYLE_1_ACCENT_3 = 'DarkStyle1Accent3'  # Dark Style 1 - Accent 3.
    DARK_STYLE_1_ACCENT_4 = 'DarkStyle1Accent4'  # Dark Style 1 - Accent 4.
    DARK_STYLE_1_ACCENT_5 = 'DarkStyle1Accent5'  # Dark Style 1 - Accent 5.
    DARK_STYLE_1_ACCENT_6 = 'DarkStyle1Accent6'  # Dark Style 1 - Accent 6.
    DARK_STYLE2 = 'DarkStyle2'  # Dark Style 2.
    DARK_STYLE_2_ACCENT_1_ACCENT_2 = 'DarkStyle2Accent1Accent2'  # Dark Style 2 - Accent 1/Accent 2.
    DARK_STYLE_2_ACCENT_3_ACCENT_4 = 'DarkStyle2Accent3Accent4'  # Dark Style 2 - Accent 3/Accent 4.
    DARK_STYLE_2_ACCENT_5_ACCENT_6 = 'DarkStyle2Accent5Accent6'  # Dark Style 2 - Accent 5/Accent 6.
    LIGHT_STYLE_1_ACCENT_5 = 'LightStyle1Accent5'  # Light Style 1 - Accent 5.
