from __future__ import annotations
from enum import Enum
class TransitionType(Enum):
    """Represent slide show transition type."""
    NONE = 'None'
    BLINDS = 'Blinds'
    CHECKER = 'Checker'
    CIRCLE = 'Circle'  # Relates to transition Shape (with option Circle) in PowerPoint 2010.
    COMB = 'Comb'
    COVER = 'Cover'
    CUT = 'Cut'
    DIAMOND = 'Diamond'  # Relates to transition Shape (with option Diamond) in PowerPoint 2010.
    DISSOLVE = 'Dissolve'
    FADE = 'Fade'
    NEWSFLASH = 'Newsflash'
    PLUS = 'Plus'  # Relates to transition Shape (with option Plus) in PowerPoint 2010.
    PULL = 'Pull'
    PUSH = 'Push'
    RANDOM = 'Random'
    RANDOM_BAR = 'RandomBar'
    SPLIT = 'Split'  # Equivalent to transition Wipe in PowerPoint 2010.
    STRIPS = 'Strips'
    WEDGE = 'Wedge'  # Relates to transition Clock (with option Wedge) in PowerPoint 2010.
    WHEEL = 'Wheel'  # Relates to transition Clock (with option Clockwise) in PowerPoint 2010.
    WIPE = 'Wipe'
    ZOOM = 'Zoom'  # Relates to transition Shape (with options In/Out) in PowerPoint 2010. See also that relates to transition Zoom in PowerPoint 2010.
    VORTEX = 'Vortex'  # Available in PowerPoint 2010.
    SWITCH = 'Switch'  # Available in PowerPoint 2010.
    FLIP = 'Flip'  # Available in PowerPoint 2010.
    RIPPLE = 'Ripple'  # Available in PowerPoint 2010.
    HONEYCOMB = 'Honeycomb'  # Available in PowerPoint 2010.
    CUBE = 'Cube'  # Available in PowerPoint 2010.
    BOX = 'Box'  # Available in PowerPoint 2010.
    ROTATE = 'Rotate'  # Available in PowerPoint 2010.
    ORBIT = 'Orbit'  # Available in PowerPoint 2010.
    DOORS = 'Doors'  # Available in PowerPoint 2010.
    WINDOW = 'Window'  # Available in PowerPoint 2010.
    FERRIS = 'Ferris'  # Available in PowerPoint 2010.
    GALLERY = 'Gallery'  # Available in PowerPoint 2010.
    CONVEYOR = 'Conveyor'  # Available in PowerPoint 2010.
    PAN = 'Pan'  # Available in PowerPoint 2010.
    GLITTER = 'Glitter'  # Available in PowerPoint 2010.
    WARP = 'Warp'  # Relates to transition Zoom in PowerPoint 2010. Available in PowerPoint 2010.
    FLYTHROUGH = 'Flythrough'  # Available in PowerPoint 2010.
    FLASH = 'Flash'  # Available in PowerPoint 2010.
    SHRED = 'Shred'  # Available in PowerPoint 2010.
    REVEAL = 'Reveal'  # Available in PowerPoint 2010.
    WHEEL_REVERSE = 'WheelReverse'  # Relates to transition Clock (with option Counterclockwise) in PowerPoint 2010. Available in PowerPoint 2010.
    FALL_OVER = 'FallOver'  # Available in PowerPoint 2013.
    DRAPE = 'Drape'  # Available in PowerPoint 2013.
    CURTAINS = 'Curtains'  # Available in PowerPoint 2013.
    WIND = 'Wind'  # Available in PowerPoint 2013.
    PRESTIGE = 'Prestige'  # Available in PowerPoint 2013.
    FRACTURE = 'Fracture'  # Available in PowerPoint 2013.
    CRUSH = 'Crush'  # Available in PowerPoint 2013.
    PEEL_OFF = 'PeelOff'  # Available in PowerPoint 2013.
    PAGE_CURL_DOUBLE = 'PageCurlDouble'  # Available in PowerPoint 2013.
    PAGE_CURL_SINGLE = 'PageCurlSingle'  # Available in PowerPoint 2013.
    AIRPLANE = 'Airplane'  # Available in PowerPoint 2013.
    ORIGAMI = 'Origami'  # Available in PowerPoint 2013.
    MORPH = 'Morph'  # Relates to transition Morph (with option Type) in PowerPoint 2019.
