"""Constants of markdown converting formats."""

BOLD_TEXT = '**{0}**'

COMMENT_TEXT = '{0}: "{1}"'

ELEMENT_END = '{0}  {1}'

ELEMENT_WITH_NEW_LINES_BETWEEN_IT = '{1}{0}  {1}'

EMPTY_TEXT = '&nbsp;'

HEADER_CHAR = '#'

HEADER_CHAR_USING_EQUAL = '='

HEADER_HEIGHT = 10

HEADER_TEXT = '{0} {1}'

HORIZONTAL_LINE = '---'

IGNORE_RESERVED_CHAR = '\\'

IGNORE_RESERVED_CHAR_USING_TILDE = '~'

ITALIC_SLASHES_TEXT = '//{0}//'

ITALIC_TEXT = '*{0}*'

LIST_FIRST_SYMBOL_FOUR_TIMES = 4

LIST_FIRST_SYMBOL_ONE_TIME = 1

NEW_LINE_MAC = '\r'

NEW_LINE_UNIX = '\n'

ORDERED_LIST_CHAR_ONE = '1'

ORDERED_LIST_TEXT = '{0}1. {1}'

ORDERED_LIST_TEXT_USING_BRACKETS = '{0}1. ((({1})))'

SPACE_CHAR = ' '

SINGLE_NBSP_SPACE_CHARS = '     '

DOUBLE_NBSP_SPACE_CHARS = '  '

STRIKETHROUGH_TEXT = '~~{0}~~'

STRIKETHROUGH_TEXT_USING_DOUBLE_DASHES = '--{0}--'

STRIKETHROUGH_USING_DASHES_AND_CURLY_BRACKETS = '{{--{0}--}}'

SUB_TITLE_HEIGHT = 24

TABLE_COLUMN_CENTER_ALIGNMENT_DIVIDER = ':-:|'

TABLE_COLUMN_DIVIDER = '|'

TABLE_COLUMN_LEFT_ALIGNMENT_DIVIDER = '-|'

TABLE_COLUMN_RIGHT_ALIGNMENT_DIVIDER = '-:|'

TITLE_HEIGHT = 40

UNDERLINED = '{{=={0}==}}'

UNDERLINED_USING_DOUBLE_UNDER_DASHES = '__{0}__'

UNDERLINED_USING_EQUALS = '=={0}=='

UNORDERED_LIST_CHAR_USING_STAR = '*'

UNORDERED_LIST_TEXT = '{0}- {1}'

UNORDERED_LIST_TEXT_USING_BRACKETS = '{0}* ((({1})))'

SLIDE_NUMBER_FORMAT = '# {0}'
