from __future__ import annotations
from enum import Enum

class EffectSubtype(Enum):
    """Represents subtypes of animation effect."""
    NONE = 'None'
    ACROSS = 'Across'
    BOTTOM = 'Bottom'
    BOTTOM_LEFT = 'BottomLeft'
    BOTTOM_RIGHT = 'BottomRight'
    CENTER = 'Center'
    OBJECT_CENTER = 'ObjectCenter'
    SLIDE_CENTER = 'SlideCenter'
    CLOCKWISE = 'Clockwise'
    COUNTER_CLOCKWISE = 'CounterClockwise'
    GRADUAL_AND_CYCLE_CLOCKWISE = 'GradualAndCycleClockwise'
    GRADUAL_AND_CYCLE_COUNTER_CLOCKWISE = 'GradualAndCycleCounterClockwise'
    DOWN = 'Down'
    DOWN_LEFT = 'DownLeft'
    DOWN_RIGHT = 'DownRight'
    FONT_ALL_CAPS = 'FontAllCaps'
    FONT_BOLD = 'FontBold'
    FONT_ITALIC = 'FontItalic'
    FONT_SHADOW = 'FontShadow'
    FONT_STRIKETHROUGH = 'FontStrikethrough'
    FONT_UNDERLINE = 'FontUnderline'
    GRADUAL = 'Gradual'
    HORIZONTAL = 'Horizontal'
    HORIZONTAL_IN = 'HorizontalIn'
    HORIZONTAL_OUT = 'HorizontalOut'
    IN = 'In'
    IN_BOTTOM = 'InBottom'
    IN_CENTER = 'InCenter'
    IN_SLIGHTLY = 'InSlightly'
    INSTANT = 'Instant'
    LEFT = 'Left'
    ORDINAL_MASK = 'OrdinalMask'
    OUT = 'Out'
    OUT_BOTTOM = 'OutBottom'
    OUT_CENTER = 'OutCenter'
    OUT_SLIGHTLY = 'OutSlightly'
    RIGHT = 'Right'
    SLIGHTLY = 'Slightly'
    TOP = 'Top'
    TOP_LEFT = 'TopLeft'
    TOP_RIGHT = 'TopRight'
    UP = 'Up'
    UP_LEFT = 'UpLeft'
    UP_RIGHT = 'UpRight'
    VERTICAL = 'Vertical'
    VERTICAL_IN = 'VerticalIn'
    VERTICAL_OUT = 'VerticalOut'
    WHEEL1 = 'Wheel1'
    WHEEL2 = 'Wheel2'
    WHEEL3 = 'Wheel3'
    WHEEL4 = 'Wheel4'
    WHEEL8 = 'Wheel8'
