from __future__ import annotations
from enum import Enum

class EffectType(Enum):
    """Represents the type of an animation effect."""
    APPEAR = 'Appear'  # Appear effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    CURVE_UP_DOWN = 'CurveUpDown'  # CurveUpDown effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    ASCEND = 'Ascend'  # Ascend effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    FLOAT_UP = 'FloatUp'  # Float effect with direction Up. This is the alias for Ascend type. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    BLAST = 'Blast'  # Blast effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    BLINDS = 'Blinds'  # Blinds effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.HorizontalEffectSubtype.Vertical
    BLINK = 'Blink'  # Blink effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    BOLD_FLASH = 'BoldFlash'  # BoldFlash effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    BOLD_REVEAL = 'BoldReveal'  # BoldReveal effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    BOOMERANG = 'Boomerang'  # Boomerang effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    BOUNCE = 'Bounce'  # Bounce effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    BOX = 'Box'  # Box effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.InEffectSubtype.Out
    BRUSH_ON_COLOR = 'BrushOnColor'  # BrushOnColor effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    BRUSH_ON_UNDERLINE = 'BrushOnUnderline'  # BrushOnUnderline effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    CENTER_REVOLVE = 'CenterRevolve'  # CenterRevolve effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    CHANGE_FILL_COLOR = 'ChangeFillColor'  # ChangeFillColor effect. Class Emphasis.Valid subtypes:EffectSubtype.InstantEffectSubtype.GradualEffectSubtype.GradualAndCycleClockwiseEffectSubtype.GradualAndCycleCounterClockwise
    CHANGE_FONT = 'ChangeFont'  # ChangeFont effect. Class Emphasis.Valid subtypes:EffectSubtype.InstantEffectSubtype.Gradual
    CHANGE_FONT_COLOR = 'ChangeFontColor'  # ChangeFontColor effect. Class Emphasis.Valid subtypes:EffectSubtype.InstantEffectSubtype.GradualEffectSubtype.GradualAndCycleClockwiseEffectSubtype.GradualAndCycleCounterClockwise
    CHANGE_FONT_SIZE = 'ChangeFontSize'  # ChangeFontSize effect. Class Emphasis.Valid subtypes:EffectSubtype.InstantEffectSubtype.Gradual
    CHANGE_FONT_STYLE = 'ChangeFontStyle'  # ChangeFontSize effect. Class Emphasis.Valid subtypes:EffectSubtype.FontBoldEffectSubtype.FontItalicEffectSubtype.FontUnderline
    CHANGE_LINE_COLOR = 'ChangeLineColor'  # ChangeLineColor effect. Class Emphasis.Valid subtypes:EffectSubtype.InstantEffectSubtype.GradualEffectSubtype.GradualAndCycleClockwiseEffectSubtype.GradualAndCycleCounterClockwise
    CHECKERBOARD = 'Checkerboard'  # Checkerboard effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.VerticalEffectSubtype.Across
    CIRCLE = 'Circle'  # ColorBlend effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.InEffectSubtype.Out
    COLOR_BLEND = 'ColorBlend'  # BrushOnUnderline effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    COLOR_TYPEWRITER = 'ColorTypewriter'  # Checkerboard effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    COLOR_WAVE = 'ColorWave'  # ColorWave effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    COMPLEMENTARY_COLOR = 'ComplementaryColor'  # ComplementaryColor effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    COMPLEMENTARY_COLOR2 = 'ComplementaryColor2'  # ComplementaryColor2 effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    COMPRESS = 'Compress'  # Compress effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    CONTRASTING_COLOR = 'ContrastingColor'  # ContrastingColor effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    CRAWL = 'Crawl'  # Crawl effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.RightEffectSubtype.LeftEffectSubtype.TopEffectSubtype.Bottom
    CREDITS = 'Credits'  # Credits effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    CUSTOM = 'Custom'  # Custom effect.
    DARKEN = 'Darken'  # Darken effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    DESATURATE = 'Desaturate'  # Desaturate effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    DESCEND = 'Descend'  # Descend effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    FLOAT_DOWN = 'FloatDown'  # Float effect with direction Down. This is the alias for Descend type. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    DIAMOND = 'Diamond'  # Diamond effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.InEffectSubtype.Out
    DISSOLVE = 'Dissolve'  # Dissolve effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    EASE_IN_OUT = 'EaseInOut'  # Dissolve effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    EXPAND = 'Expand'  # Expand effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    FADE = 'Fade'  # Fade effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    FADED_SWIVEL = 'FadedSwivel'  # FadedSwivel effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    FADED_ZOOM = 'FadedZoom'  # FadedZoom effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    FLASH_BULB = 'FlashBulb'  # FlashBulb effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    FLASH_ONCE = 'FlashOnce'  # FlashOnce effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    FLICKER = 'Flicker'  # Flicker effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    FLIP = 'Flip'  # Flip effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    FLOAT = 'Float'  # Float effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    FLY = 'Fly'  # Fly effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.RightEffectSubtype.LeftEffectSubtype.TopEffectSubtype.BottomEffectSubtype.TopLeftEffectSubtype.TopRightEffectSubtype.BottomLeftEffectSubtype.BottomRight
    FOLD = 'Fold'  # Fold effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    GLIDE = 'Glide'  # Glide effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    GROW_AND_TURN = 'GrowAndTurn'  # GrowAndTurn effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    GROW_SHRINK = 'GrowShrink'  # GrowShrink effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    GROW_WITH_COLOR = 'GrowWithColor'  # GrowWithColor effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    LIGHTEN = 'Lighten'  # Lighten effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    LIGHT_SPEED = 'LightSpeed'  # LightSpeed effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    MEDIA_PAUSE = 'MediaPause'  # MediaPause effect. Class Media.Valid subtypes:EffectSubtype.None
    MEDIA_PLAY = 'MediaPlay'  # MediaPlay effect. Class Media.Valid subtypes:EffectSubtype.None
    MEDIA_STOP = 'MediaStop'  # MediaStop effect. Class Media.Valid subtypes:EffectSubtype.None
    PATH_4_POINT_STAR = 'Path4PointStar'  # Path4PointStar effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_5_POINT_STAR = 'Path5PointStar'  # Path5PointStar effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_6_POINT_STAR = 'Path6PointStar'  # Path6PointStar effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_8_POINT_STAR = 'Path8PointStar'  # Path8PointStar effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_ARC_DOWN = 'PathArcDown'  # PathArcDown effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_ARC_LEFT = 'PathArcLeft'  # PathArcLeft effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_ARC_RIGHT = 'PathArcRight'  # PathArcRight effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_ARC_UP = 'PathArcUp'  # PathArcUp effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_BEAN = 'PathBean'  # PathBean effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_BOUNCE_LEFT = 'PathBounceLeft'  # PathBounceLeft effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_BOUNCE_RIGHT = 'PathBounceRight'  # PathBounceRight effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_BUZZSAW = 'PathBuzzsaw'  # PathBuzzsaw effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_CIRCLE = 'PathCircle'  # PathCircle effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_CRESCENT_MOON = 'PathCrescentMoon'  # PathCrescentMoon effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_CURVED_SQUARE = 'PathCurvedSquare'  # PathCurvedSquare effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_CURVED_X = 'PathCurvedX'  # PathCurvedX effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_CURVY_LEFT = 'PathCurvyLeft'  # PathCurvyLeft effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_CURVY_RIGHT = 'PathCurvyRight'  # PathCurvyRight effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_CURVY_STAR = 'PathCurvyStar'  # PathCurvyStar effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_DECAYING_WAVE = 'PathDecayingWave'  # PathDecayingWave effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_DIAGONAL_DOWN_RIGHT = 'PathDiagonalDownRight'  # PathDiagonalDownRight effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_DIAGONAL_UP_RIGHT = 'PathDiagonalUpRight'  # PathDiagonalUpRight effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_DIAMOND = 'PathDiamond'  # PathDiamond effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_DOWN = 'PathDown'  # PathDown effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_EQUAL_TRIANGLE = 'PathEqualTriangle'  # PathEqualTriangle effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_FIGURE_8_FOUR = 'PathFigure8Four'  # PathFigure8Four effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_FOOTBALL = 'PathFootball'  # PathFootball effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_FUNNEL = 'PathFunnel'  # PathFunnel effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_HEART = 'PathHeart'  # PathHeart effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_HEARTBEAT = 'PathHeartbeat'  # PathHeartbeat effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_HEXAGON = 'PathHexagon'  # PathHexagon effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_HORIZONTAL_FIGURE8 = 'PathHorizontalFigure8'  # PathHorizontalFigure8 effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_INVERTED_SQUARE = 'PathInvertedSquare'  # PathInvertedSquare effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_INVERTED_TRIANGLE = 'PathInvertedTriangle'  # PathInvertedTriangle effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_LEFT = 'PathLeft'  # PathLeft effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_LOOPDE_LOOP = 'PathLoopdeLoop'  # PathLoopdeLoop effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_NEUTRON = 'PathNeutron'  # PathNeutron effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_OCTAGON = 'PathOctagon'  # PathOctagon effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_PARALLELOGRAM = 'PathParallelogram'  # PathParallelogram effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_PEANUT = 'PathPeanut'  # PathPeanut effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_PENTAGON = 'PathPentagon'  # PathPentagon effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_PLUS = 'PathPlus'  # PathPlus effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_POINTY_STAR = 'PathPointyStar'  # PathPointyStar effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_RIGHT = 'PathRight'  # PathRight effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_RIGHT_TRIANGLE = 'PathRightTriangle'  # PathRightTriangle effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_S_CURVE1 = 'PathSCurve1'  # PathSCurve1 effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_S_CURVE2 = 'PathSCurve2'  # PathSCurve2 effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_SINE_WAVE = 'PathSineWave'  # PathSineWave effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_SPIRAL_LEFT = 'PathSpiralLeft'  # PathSpiralLeft effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_SPIRAL_RIGHT = 'PathSpiralRight'  # PathSpiralRight effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_SPRING = 'PathSpring'  # PathSpring effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_SQUARE = 'PathSquare'  # PathSquare effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_STAIRS_DOWN = 'PathStairsDown'  # PathStairsDown effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_SWOOSH = 'PathSwoosh'  # PathSwoosh effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_TEARDROP = 'PathTeardrop'  # PathTeardrop effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_TRAPEZOID = 'PathTrapezoid'  # PathTrapezoid effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_TURN_DOWN = 'PathTurnDown'  # PathTurnDown effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_TURN_RIGHT = 'PathTurnRight'  # PathTurnRight effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_TURN_UP = 'PathTurnUp'  # PathTurnUp effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_TURN_UP_RIGHT = 'PathTurnUpRight'  # PathTurnUpRight effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_UP = 'PathUp'  # PathUp effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_USER = 'PathUser'  # PathUser effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_VERTICAL_FIGURE8 = 'PathVerticalFigure8'  # PathVerticalFigure8 effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_WAVE = 'PathWave'  # PathWave effect. Class Path.Valid subtypes:EffectSubtype.None
    PATH_ZIGZAG = 'PathZigzag'  # PathZigzag effect. Class Path.Valid subtypes:EffectSubtype.None
    PEEK = 'Peek'  # Peek effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    PINWHEEL = 'Pinwheel'  # Pinwheel effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    PLUS = 'Plus'  # Plus effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.InEffectSubtype.Out
    RANDOM_BARS = 'RandomBars'  # RandomBars effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.HorizontalEffectSubtype.Vertical
    RANDOM_EFFECTS = 'RandomEffects'  # RandomEffects effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    RISE_UP = 'RiseUp'  # RandomEffects effect. Class Entrance.Valid subtypes:EffectSubtype.None
    SHIMMER = 'Shimmer'  # Shimmer effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    SLING = 'Sling'  # RandomEffects effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    SPIN = 'Spin'  # Spin effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    SPINNER = 'Spinner'  # Spinner effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    SPIRAL = 'Spiral'  # Spiral effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    SPLIT = 'Split'  # Split effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.HorizontalInEffectSubtype.HorizontalOutEffectSubtype.VerticalInEffectSubtype.VerticalOut
    STRETCH = 'Stretch'  # Stretch effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.RightEffectSubtype.LeftEffectSubtype.TopEffectSubtype.BottomEffectSubtype.Across
    STRIPS = 'Strips'  # Stretch effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.UpLeftEffectSubtype.UpRightEffectSubtype.DownLeftEffectSubtype.DownRight
    STYLE_EMPHASIS = 'StyleEmphasis'  # StyleEmphasis effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    SWISH = 'Swish'  # Swish effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    SWIVEL = 'Swivel'  # Swivel effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.HorizontalEffectSubtype.Vertical
    TEETER = 'Teeter'  # Teeter effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    THREAD = 'Thread'  # Thread effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    TRANSPARENCY = 'Transparency'  # Transparency effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    UNFOLD = 'Unfold'  # Unfold effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    VERTICAL_GROW = 'VerticalGrow'  # VerticalGrow effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    WAVE = 'Wave'  # Wave effect. Class Emphasis.Valid subtypes:EffectSubtype.None
    WEDGE = 'Wedge'  # Wedge effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    WHEEL = 'Wheel'  # Wedge effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.Wheel1EffectSubtype.Wheel2EffectSubtype.Wheel3EffectSubtype.Wheel4EffectSubtype.Wheel8
    WHIP = 'Whip'  # Whip effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    WIPE = 'Wipe'  # Wedge effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.TopEffectSubtype.RightEffectSubtype.BottomEffectSubtype.Left
    MAGNIFY = 'Magnify'  # Magnify effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.None
    ZOOM = 'Zoom'  # Zoom effect. Class Entrance or Exit.Valid subtypes:EffectSubtype.InEffectSubtype.OutEffectSubtype.InCenter - only for Entrance classEffectSubtype.OutBottom - only for Entrance classEffectSubtype.OutSlightlyEffectSubtype.InSlightlyEffectSubtype.OutCenter - only for Exit classEffectSubtype.InBottom - only for Exit class
    OLE_OBJECT_SHOW = 'OLEObjectShow'  # OLEObjectShow effect. Class OLEActionVerbs.Valid subtypes:EffectSubtype.None
    OLE_OBJECT_EDIT = 'OLEObjectEdit'  # OLEObjectEdit effect. Class OLEActionVerbs.Valid subtypes:EffectSubtype.None
    OLE_OBJECT_OPEN = 'OLEObjectOpen'  # OLEObjectOpen effect. Class OLEActionVerbs.Valid subtypes:EffectSubtype.None
